before_install:
  - sudo apt-get install -y wget openssl libssl-dev coreutils
  - sudo apt-get install -y build-essential ca-certificates
language: node_js
env:
  - CXX=g++-4.8
node_js:
  - 'node'
  - '8'
  - '6'
  - '5'
  - '4'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
